import { Language } from "./types";

export const LANGUAGES: { code: Language; label: string; nativeLabel: string; prompt: string }[] = [
  { code: 'en', label: 'English', nativeLabel: 'English', prompt: "How can I help you today?" },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिंदी', prompt: "आज मैं आपकी कैसे मदद कर सकता हूँ?" },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी', prompt: "मी तुम्हाला कशी मदत करू शकतो?" },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', prompt: "ఈ రోజు నేను మీకు ఎలా సహాయపడగలను?" },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', prompt: "இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?" },
];

export const MOCK_LISTINGS = [
  {
    id: '1',
    farmerId: 'f1',
    farmerName: 'Ramesh Kumar',
    cropName: 'Onion (Pyaz)',
    quantity: 500,
    price: 25,
    location: 'Nashik, Maharashtra',
    description: 'Fresh red onions, harvested yesterday.',
    timestamp: Date.now() - 100000,
  },
  {
    id: '2',
    farmerId: 'f2',
    farmerName: 'Suresh Patil',
    cropName: 'Wheat (Gehu)',
    quantity: 1000,
    price: 22,
    location: 'Pune, Maharashtra',
    description: 'High quality Lokwan wheat.',
    timestamp: Date.now() - 200000,
  },
];

export const TRANSLATIONS = {
  en: {
    welcome: "Namaste",
    roleFarmer: "Farmer (Annadata)",
    roleBuyer: "Buyer (Vyapari)",
    marketInsight: "Market Insight",
    createListing: "List New Crop",
    myListings: "My Listings",
    inbox: "Inbox",
    cropName: "Crop Name",
    quantity: "Quantity (kg)",
    price: "Price (₹/kg)",
    location: "Location",
    description: "Description",
    save: "Save Listing",
    update: "Update Listing",
    cancel: "Cancel",
    edit: "Edit",
    chat: "Chat",
    call: "Call",
    voicePlaceholder: "Tap to speak...",
    negotiate: "Negotiate / Buy",
    buy: "Buy",
    trend: "Trend",
    noListings: "No listings yet.",
    messages: "Messages",
    messageFrom: "Message from",
    tapToSpeak: "Tap to speak",
    voicePromptCreate: "I want to sell 500kg of Onions...",
    voicePromptEdit: "Change price to 30...",
    findCrops: "Find fresh crops directly from farmers",
    mandiTitle: "Mandi Marketplace",
    negotiationTitle: "Negotiation",
    typeMessage: "Type a message...",
    send: "Send",
    profile: "Profile",
    unknown: "Unknown"
  },
  hi: {
    welcome: "नमस्ते",
    roleFarmer: "किसान (अन्नदाता)",
    roleBuyer: "खरीदार (व्यापारी)",
    marketInsight: "बाजार की जानकारी",
    createListing: "नई फसल बेचें",
    myListings: "मेरी फसलें",
    inbox: "संदेश",
    cropName: "फसल का नाम",
    quantity: "मात्रा (किलो)",
    price: "कीमत (₹/किलो)",
    location: "स्थान",
    description: "विवरण",
    save: "फसल सूची में डालें",
    update: "अपडेट करें",
    cancel: "रद्द करें",
    edit: "बदलें",
    chat: "बातचीत",
    call: "कॉल करें",
    voicePlaceholder: "बोलने के लिए टैप करें...",
    negotiate: "मोलभाव / खरीदें",
    buy: "खरीदें",
    trend: "रुझान",
    noListings: "अभी तक कोई फसल नहीं है।",
    messages: "संदेश",
    messageFrom: "का संदेश",
    tapToSpeak: "बोलने के लिए टैप करें",
    voicePromptCreate: "मैं 500 किलो प्याज बेचना चाहता हूं...",
    voicePromptEdit: "कीमत 30 रुपये कर दो...",
    findCrops: "किसानों से सीधे ताजी फसलें प्राप्त करें",
    mandiTitle: "मंडी बाज़ार",
    negotiationTitle: "मोलभाव",
    typeMessage: "संदेश लिखें...",
    send: "भेजें",
    unknown: "अज्ञात"
  },
  mr: {
    welcome: "नमस्कार",
    roleFarmer: "शेतकरी (अन्नदाता)",
    roleBuyer: "खरेदीदार (व्यापारी)",
    marketInsight: "बाजार भाव",
    createListing: "नवीन पीक विक्री",
    myListings: "माझी पिके",
    inbox: "संदेश",
    cropName: "पिकाचे नाव",
    quantity: "प्रमाण (किलो)",
    price: "भाव (₹/किलो)",
    location: "स्थान",
    description: "वर्णन",
    save: "यादीत टाका",
    update: "अपडेट करा",
    cancel: "रद्द करा",
    edit: "संपादित करा",
    chat: "चर्चा",
    call: "कॉल करा",
    voicePlaceholder: "बोलण्यासाठी टॅप करा...",
    negotiate: "वाटाघाटी / खरेदी",
    buy: "खरेदी करा",
    trend: "कल",
    noListings: "अद्याप कोणतीही पिके नाहीत.",
    messages: "संदेश",
    messageFrom: "यांचा संदेश",
    tapToSpeak: "बोलण्यासाठी टॅप करा",
    voicePromptCreate: "मला 500 किलो कांदा विकायचा आहे...",
    voicePromptEdit: "भाव 30 रुपये करा...",
    findCrops: "थेट शेतकऱ्यांकडून ताजी पिके मिळवा",
    mandiTitle: "मंडी बाजारपेठ",
    negotiationTitle: "वाटाघाटी",
    typeMessage: "संदेश लिहा...",
    send: "पाठवा",
    unknown: "अज्ञात"
  },
  te: {
    welcome: "నమస్కారం",
    roleFarmer: "రైతు (అన్నదాత)",
    roleBuyer: "కొనుగోలుదారు (వ్యాపారి)",
    marketInsight: "మార్కెట్ సమాచారం",
    createListing: "కొత్త పంటను అమ్మండి",
    myListings: "నా పంటలు",
    inbox: "సందేశాలు",
    cropName: "పంట పేరు",
    quantity: "పరిమాణం (kg)",
    price: "ధర (₹/kg)",
    location: "ప్రాంతం",
    description: "వివరణ",
    save: "జాబితాలో చేర్చు",
    update: "నవీకరించు",
    cancel: "రద్దు చేయి",
    edit: "సవరించు",
    chat: "చాట్",
    call: "కాల్",
    voicePlaceholder: "మాట్లాడటానికి నొక్కండి...",
    negotiate: "బేరసారాలు / కొనండి",
    buy: "కొనండి",
    trend: "ట్రెండ్",
    noListings: "ఇంకా పంటలు లేవు.",
    messages: "సందేశాలు",
    messageFrom: "నుండి సందేశం",
    tapToSpeak: "మాట్లాడటానికి నొక్కండి",
    voicePromptCreate: "నేను 500 కిలోల ఉల్లిపాయలు అమ్మాలనుకుంటున్నాను...",
    voicePromptEdit: "ధర 30 రూపాయలకు మార్చండి...",
    findCrops: "తాజా పంటలను నేరుగా రైతుల నుండి పొందండి",
    mandiTitle: "మండి మార్కెట్",
    negotiationTitle: "బేరసారాలు",
    typeMessage: "సందేశం టైప్ చేయండి...",
    send: "పంపు",
    unknown: "తెలియదు"
  },
  ta: {
    welcome: "வணக்கம்",
    roleFarmer: "விவசாயி (அன்னதாத்தா)",
    roleBuyer: "வாங்குபவர் (வியாபாரி)",
    marketInsight: "சந்தை நிலவரம்",
    createListing: "புதிய பயிரை விற்க",
    myListings: "என் பயிர்கள்",
    inbox: "செய்திகள்",
    cropName: "பயிர் பெயர்",
    quantity: "அளவு (kg)",
    price: "விலை (₹/kg)",
    location: "இடம்",
    description: "விளக்கம்",
    save: "பட்டியலிடு",
    update: "புதுப்பி",
    cancel: "ரத்து செய்",
    edit: "திருத்து",
    chat: "உரையாடல்",
    call: "அழைப்பு",
    voicePlaceholder: "பேச தட்டவும்...",
    negotiate: "பேரம் / வாங்கு",
    buy: "வாங்கு",
    trend: "போக்கு",
    noListings: "பயிர்கள் எதுவும் இல்லை.",
    messages: "செய்திகள்",
    messageFrom: "விடமிருந்து செய்தி",
    tapToSpeak: "பேச தட்டவும்",
    voicePromptCreate: "நான் 500 கிலோ வெங்காயம் விற்க விரும்புகிறேன்...",
    voicePromptEdit: "விலையை 30 ஆக மாற்றவும்...",
    findCrops: "விவசாயிகளிடமிருந்து நேரடியாக பயிர்களைப் பெறுங்கள்",
    mandiTitle: "மண்டி சந்தை",
    negotiationTitle: "பேரம்",
    typeMessage: "செய்தியை தட்டச்சு செய்யவும்...",
    send: "அனுப்பு",
    unknown: "தெரியவில்லை"
  }
};
